### ISSUE TITLE
Is MannVsFate abandoned?

### ISSUE THREAD

**Issue by CombineSlayer24** [ByteNybbler/MannVsFate#7]
Hello there. I am just wondering if this project has been abandoned. The thought of Randomly generated missions was always fun to play. There used to be a forum posting on the Old Facepunch forums with a randomized MvM Generator. Sadly, that did not get saved from wayback machine. While mvm.tf exists with a Randomizer option, it's super basic and not fun to play against since this chooses every bot in the template, even chiefs, and always have 10 robots per subwave.

![image](https://user-images.githubusercontent.com/82725572/124152256-39f83380-da48-11eb-9003-40be4693173c.png)
This is how mvm.tf does it's randomization, it's not very interesting.

Seeing the potential of random missions from this would be amazing, even know there's ways of creating our own missions, sometimes you want something by someone else, or in this case, by Random.

With this, I'm just curious if this would ever be picked up again, if not, then I understand. Have a great day.

**Comment by ByteNybbler** [comment]
Honestly I'm surprised that someone found this project. It should work just fine if you build it. If you want to customize MannVsFate's randomization, I added all sorts of different command line options. See https://github.com/ByteNybbler/MannVsFate/blob/master/REDIST/COMMAND%20LINE%20OPTIONS.txt and the batch files in the same folder.

I agree that mvm.tf's randomization is unsatisfactory. With the proper settings, missions generated by MannVsFate are much more entertaining (in my opinion) and have provided my friends and I hours of entertainment. Sometimes I wonder if I should have released this publicly.

I have not updated MannVsFate in a long time, and I don't have any concrete plans to update it in the future since there hasn't been anything else I've really wanted to add. I consider its functionality to be mostly complete, aside from maybe a few balance issues here and there.

**Comment by CombineSlayer24** [comment]
As a mission creator myself, it gets boring, playing my own missions, you know. I found this project by just simply searching "TF2 Random MvM Wave Generator", and this GitHub happened to appear under mvm.tf. I saw that there was no compiled releases and I thought "Is this still in active development?". I did look into the possibilities with the random generation options via the command line options and the presets you made in REDIST file.

When I typed in "I'm just curious if this would ever be picked up again" I thought it was abandoned since I didn't see any releases with the compiled script. I don't know anything about building VS projects. I sadly, wouldn't know how to build it. 

Would it be possible that you could upload a compile release? Again I'm sorry to ask, I just don't know how that works, and this seems too good to pass.

**Comment by CombineSlayer24** [comment]
Also, one question. When MannVsFate is generating a random mission, does the robots get completely randomized? Is there an option for MannVsFate to pick out robots in a robot_ template file (Depending on the robot's **Skill level**), being a custom robot_myrobots.pop, or Valve's default robot templates (from Standard, Giant and Gatebot)

**Comment by CombineSlayer24** [comment]
Update: After 2 days of tinkering with Visual Studio, I was able to successfully build MannVsFate.
